version: '2'


services:
    application:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www

    redis:
        image: redis:3.2-alpine
        depends_on:
            - application

    nginx:
        image: nginx:1.10-alpine
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - application
